### ISSUE TITLE
PicoGAUpdate installed GeForce Experience

### ISSUE THREAD

**Issue by DarlCat** [Ociidii-Works/PicoGAUpdate#1]
I ran PicoGAUpdate on 7/15/2020 to get Nvidia driver v451.67 and GFE was installed alongside it. The installer format may have been updated. I have not run any installers myself, and my Windows install is configured not to download device drivers.

Expected:
GeForce Experience not to be installed alongside driver by PicoGAUpdate

![image](https://user-images.githubusercontent.com/4566791/90419943-491b0080-e085-11ea-895d-6008317b94f4.png)

**Comment by DarlCat** [comment]
To test, I ran the tool again to grab the latest update (that I noticed because of a GFE notification, ironically) after uninstalling GFE. It found its way back.
![image](https://user-images.githubusercontent.com/4566791/90421986-30601a00-e088-11ea-8506-5e8f08cda12c.png)

**Comment by XenHat** [comment]
Preventing the installation of GFE is currently outside my knowledge of the installer framework. There is a command-line switch to try to uninstall it after-the-fact but I haven't tested it in a while.

Alternatively, you can create a minimal installation package with [NVSlimmer](https://forums.guru3d.com/threads/nvslimmer-nvidia-driver-slimming-utility.423072/).

**Comment by XenHat** [comment]
@DarlCat can you test if https://github.com/Ociidii-Works/PicoGAUpdate/releases/tag/0.0.9 works ? run with `--strip` parameter. Add `--install` to force install even if up to date.

**Comment by DarlCat** [comment]
@XenHat That release combined with those flags doesn't install GFE as expected. Thanks, and good work!
